language: php

sudo: false

env:
  global:
    - RUN_PHPCS="no"
    - RUN_SCRUTINIZER="no"
    - COMPOSER_FLAGS=""
    - PHPUNIT_FLAGS=""

matrix:
  include:
    - php: 5.5
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: RUN_PHPCS="yes" RUN_SCRUTINIZER="yes" PHPUNIT_FLAGS="--coverage-clover .travis/logs/clover.xml"
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: 7.1
    - php: hhvm

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then mkdir -p .travis/logs; fi;
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover .travis/logs/clover.xml; fi;
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/; fi;
